name: Daily Deploy
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: |
          npm ci --no-optional
      - name: Build
        run: |
          npm run build
      - name: Deploy
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --message \"${{ github.event.head_commit.message }}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
